export const portfolioData = [
    // {
    //     title: "Space Invaders",
    //     image: "../../img/SpaceInvader.png",
    //     type: "Web 2",
    //     link: "https://www.youtube.com/watch?v=ec8vSKJuZTk&t=14931s",
    //     author: "Ania Kubów",
    // },
    {
        title: "Certificate",
        image: {
            src: "../../img/JavaCourse.png",
            srcset: "",
            alt: "Full Stack Course",
        },
        type: "Course",
        section: "Java",
        link: "https://www.udemy.com/certificate/UC-873f7935-7ffe-4f98-a600-27cbd3d898b6/",
        author: "Udemy",
    },
    {
        title: "Certificate",
        image: {
            src: "../../img/solidity.jpg",
            srcset: "",
            alt: "Solidity Course",
        },
        type: "Course",
        section: "Solidity",
        link: "https://www.udemy.com/certificate/UC-f1fc04e1-8294-45ef-882d-cd8e482862ef/?utm_campaign=email",
        author: "Udemy",
    },
    {
        title: "Recap",
        image: {
            src: "../../img/impatient-js.jpg",
            srcset: "",
            alt: "Impatient JavaScript",
        },
        type: "Book",
        section: "JavaScript",
        link: "https://exploringjs.com/impatient-js/toc.html",
        author: "Dr. Axel Rauschmayer",
    },
    {
        title: "Nice One",
        image: {
            src: "../../img/deep-javascript.jpg",
            srcset: "",
            alt: "Deep JavaScript",
        },
        type: "Book",
        section: "JavaScript",
        link: "https://exploringjs.com/deep-js/toc.html",
        author: "Dr. Axel Rauschmayer",
    },
    {
        title: "Recommend",
        image: {
            src: "../../img/shell-scripting.jpg",
            srcset: "",
            alt: "Node.Js Shell Scripting",
        },
        type: "Book",
        section: "JavaScript",
        link: "https://exploringjs.com/nodejs-shell-scripting/toc.html",
        author: "Dr. Axel Rauschmayer",
    },
    {
        title: "Portfolio",
        image: {
            src: "../../img/portfolio.png",
            srcset: "",
            alt: "Portfolio",
        },
        type: "Project",
        section: "Portfolio",
        link: "https://www.github.com/huesoskywalker/portfolio-javascript-vanilla",
        author: "huesoskywalker",
    },
    {
        title: "Certificate",
        image: {
            src: "../../img/datastructure.jpg",
            srcset: "",
            alt: "Data Structure",
        },
        type: "Course",
        section: "Data Structure",
        link: "https://www.udemy.com/certificate/UC-0fb3ba80-5b92-432a-bb9d-c99a11114225/",
        author: "Udemy",
    },
    {
        title: "Practitioner",
        image: {
            src: "../../img/cloud-practitioner.png",
            srcset: "",
            alt: "Cloud Practitioner",
        },
        type: "Course",
        section: "AWS",
        link: "https://www.udemy.com/certificate/UC-e478599a-70b3-4041-bdbe-43d69e9e1e05/",
        author: "Udemy",
    },
    {
        title: "DevOps",
        image: {
            src: "../../img/DevOps.png",
            srcset: "",
            alt: "DevOps",
        },
        type: "Course",
        section: "DevOps",
        link: "https://www.udemy.com/certificate/UC-3b45d537-6ab3-4aa5-a259-31a44164ea0a/",
        author: "Udemy",
    },
    {
        title: "Chat",
        image: {
            src: "../../img/real-time-chat.png",
            srcset: "",
            alt: "Chat App Project",
        },
        type: "Project",
        section: "Viper",
        link: "https://www.youtube.com/watch?v=-Y1cdWwqD_o",
        author: "huesoskywalker",
    },
    {
        title: "Cypress",
        image: {
            src: "../../img/cypress-e2e.png",
            srcset: "",
            alt: "Cypress test",
        },
        type: "Project",
        section: "Viper",
        link: "https://youtu.be/Vnpv851Q6Pc",
        author: "huesoskywalker",
    },
    {
        title: "Shopify",
        image: {
            src: "../../img/shopify-viper.jpg",
            srcset: "",
            alt: "Shopify Integration",
        },
        type: "Project",
        section: "Viper",
        link: "https://www.youtube.com/watch?v=Cnmtfi2yzQg",
        author: "huesoskywalker",
    },
    {
        title: "Full Stack",
        image: {
            src: "../../img/viper-13b.png",
            srcset: "",
            alt: "Full Stack App",
        },
        type: "Project",
        section: "Viper",
        link: "https://youtu.be/nlp_7W6O2B4",
        author: "husoskywalker",
    },
    {
        title: "Only API's",
        image: {
            src: "../../img/viper.jpg",
            srcset: "",
            alt: "RESTful API's",
        },
        type: "Project",
        section: "Viper",
        link: "https://github.com/huesoskywalker/viper-nextjs-mongodb",
        author: "huesoskywalker",
    },

    {
        title: "Entry point",
        image: {
            src: "../../img/typescript.png",
            srcset: "",
            alt: "TypeScript Book",
        },
        type: "Book",
        section: "JavaScript",
        link: "https://www.typescriptlang.org/docs/handbook/intro.html",
        author: "typescriptlang.org",
    },
    {
        title: "Real State Map",
        image: {
            src: "../../img/google-maps-api.png",
            srcset: "",
            alt: "Real State Map",
        },
        type: "Project",
        section: "Google Maps API",
        link: "https://www.youtube.com/watch?v=USTM_HdKN2I",
        author: "huesoskywalker",
    },
    {
        title: "Chicago Medical",
        image: {
            src: "../../img/chicago-medical.jpg",
            srcset: "",
            alt: "Chicago Medial",
        },
        type: "Project",
        section: "Chicago Medical",
        link: "https://chicago-medical-checkup.vercel.app/",
        author: "huesoskywalker",
    },
]
