export const portfolioData = [
    {
        title: "Certificate",
        image: {
            src: "/img/portfolio/wide/full-stack_1920w.jpg",
            srcset: "/img/portfolio/wide/full-stack_1920w.jpg 1920w, /img/portfolio/wide/full-stack_768w.jpg 768w",
            alt: "Full Stack Course",
        },
        type: "Course",
        section: "FullStack",
        date: new Date("2021-07-01"),
        link: "https://www.udemy.com/certificate/UC-873f7935-7ffe-4f98-a600-27cbd3d898b6/",
        author: "Udemy",
    },
    {
        title: "Portfolio",
        image: {
            src: "/img/portfolio/wide/portfolio_1920w.jpg",
            srcset: "/img/portfolio/wide/portfolio_1920w.jpg 1920w, /img/portfolio/wide/portfolio_768w.jpg 768w",
            alt: "Portfolio",
        },
        type: "Project",
        section: "Web Development",
        date: new Date("2022-08-01"),
        link: "https://www.github.com/huesoskywalker/portfolio-javascript-vanilla",
        author: "huesoskywalker",
    },
    {
        title: "Certificate",
        image: {
            src: "/img/portfolio/wide/blockchain_1920w.jpg",
            srcset: "/img/portfolio/wide/blockchain_1920w.jpg 1920w, /img/portfolio/wide/blockchain_768w.jpg 768w",
            alt: "Solidity Course",
        },
        type: "Course",
        section: "Blockchain",
        date: new Date("2022-08-22"),
        link: "https://www.udemy.com/certificate/UC-f1fc04e1-8294-45ef-882d-cd8e482862ef/?utm_campaign=email",
        author: "Udemy",
    },
    {
        title: "Recap",
        image: {
            src: "/img/portfolio/tall/impatient-programmer_1920w.jpg",
            srcset: "/img/portfolio/tall/impatient-programmer_1920w.jpg 1920w, /img/portfolio/tall/impatient-programmer_768w.jpg 768w",
            alt: "Impatient JavaScript",
        },
        type: "Book",
        date: new Date("2022-10-01"),
        section: "JavaScript",
        link: "https://exploringjs.com/impatient-js/toc.html",
        author: "Dr. Axel Rauschmayer",
    },
    {
        title: "Nice One",
        image: {
            src: "/img/portfolio/tall/deep-js_1920w.jpg",
            srcset: "/img/portfolio/tall/deep-js_1920w.jpg 1920w, /img/portfolio/tall/deep-js_768w.jpg 768w",
            alt: "Deep JavaScript",
        },
        type: "Book",
        section: "JavaScript",
        date: new Date("2022-11-01"),
        link: "https://exploringjs.com/deep-js/toc.html",
        author: "Dr. Axel Rauschmayer",
    },
    {
        title: "Recommend",
        image: {
            src: "/img/portfolio/tall/shell-scripting_1920w.jpg",
            srcset: "/img/portfolio/tall/shell-scripting_1920w.jpg 1920w, /img/portfolio/tall/shell-scripting_768w.jpg 768w",
            alt: "Node.Js Shell Scripting",
        },
        type: "Book",
        section: "JavaScript",
        date: new Date("2022-12-01"),
        link: "https://exploringjs.com/nodejs-shell-scripting/toc.html",
        author: "Dr. Axel Rauschmayer",
    },
    {
        title: "Great OOP",
        image: {
            src: "/img/portfolio/tall/javascript-oop_1920w.jpg",
            srcset: "/img/portfolio/tall/javascript-oop_1920w.jpg 1920w, /img/portfolio/tall/javascript-oop_768w.jpg 768w",
            alt: "Node.Js Shell Scripting",
        },
        type: "Book",
        section: "JavaScript",
        date: new Date("2023-11-01"),
        link: "",
        author: "Nicholas C. Zakas",
    },
    {
        title: "Certificate",
        image: {
            src: "/img/portfolio/wide/data-structure_1920w.jpg",
            srcset: "/img/portfolio/wide/data-structure_1920w.jpg 1920w, /img/portfolio/wide/data-structure_768w.jpg 768w",
            alt: "Algorithms & Data Structure",
        },
        type: "Course",
        section: "Algorithm & DS",
        date: new Date("2022-10-18"),
        link: "https://www.udemy.com/certificate/UC-0fb3ba80-5b92-432a-bb9d-c99a11114225/",
        author: "Udemy",
    },
    {
        title: "Practitioner",
        image: {
            src: "/img/portfolio/wide/cloud-practitioner_1920w.jpg",
            srcset: "/img/portfolio/wide/cloud-practitioner_1920w.jpg 1920w, /img/portfolio/wide/cloud-practitioner_768w.jpg 768w",
            alt: "Cloud Practitioner",
        },
        type: "Course",
        section: "AWS",
        date: new Date("2023-06-27"),
        link: "https://www.udemy.com/certificate/UC-e478599a-70b3-4041-bdbe-43d69e9e1e05/",
        author: "Udemy",
    },
    {
        title: "DevOps",
        image: {
            src: "/img/portfolio/wide/devops_1920w.jpg",
            srcset: "/img/portfolio/wide/devops_1920w.jpg 1920w, /img/portfolio/wide/devops_768w.jpg 768w",
            alt: "DevOps",
        },
        type: "Course",
        section: "DevOps",
        date: new Date("2023-09-21"),
        link: "https://www.udemy.com/certificate/UC-3b45d537-6ab3-4aa5-a259-31a44164ea0a/",
        author: "Udemy",
    },
    {
        title: "Chat",
        image: {
            src: "/img/portfolio/wide/real-time-chat_1920w.jpg",
            srcset: "/img/portfolio/wide/real-time-chat_1920w.jpg 1920w, /img/portfolio/wide/real-time-chat_768w.jpg 768w",
            alt: "Chat App Project",
        },
        type: "Project",
        section: "Viper",
        date: new Date("2023-08-20"),
        link: "https://www.youtube.com/watch?v=-Y1cdWwqD_o",
        author: "huesoskywalker",
    },
    {
        title: "Shopify",
        image: {
            src: "/img/portfolio/wide/viper-shopify_1920w.jpg",
            srcset: "/img/portfolio/wide/viper-shopify_1920w.jpg 1920w, /img/portfolio/wide/viper-shopify_768w.jpg 768w",
            alt: "Shopify Integration",
        },
        type: "Project",
        section: "Viper",
        date: new Date("2023-04-10"),
        link: "https://www.youtube.com/watch?v=Cnmtfi2yzQg",
        author: "huesoskywalker",
    },
    {
        title: "Full Stack",
        image: {
            src: "/img/portfolio/wide/viper-full-stack_1920w.jpg",
            srcset: "/img/portfolio/wide/viper-full-stack_1920w.jpg, /img/portfolio/wide/viper-full-stack_768w.jpg 768w",
            alt: "Full Stack App",
        },
        type: "Project",
        section: "Viper",
        date: new Date("2023-03-10"),
        link: "https://youtu.be/nlp_7W6O2B4",
        author: "husoskywalker",
    },
    {
        title: "Cypress",
        image: {
            src: "/img/portfolio/wide/cypress_1920w.jpg",
            srcset: "/img/portfolio/wide/cypress_1920w.jpg 1920w, /img/portfolio/wide/cypress_768w.jpg 768w",
            alt: "Cypress test",
        },
        type: "Project",
        section: "Viper",
        date: new Date("2023-06-10"),
        link: "https://youtu.be/Vnpv851Q6Pc",
        author: "huesoskywalker",
    },
    {
        title: "Only API's",
        image: {
            src: "/img/portfolio/wide/next-12-api_1920w.jpg",
            srcset: "/img/portfolio/wide/next-12-api_1920w.jpg 1920w, /img/portfolio/wide/next-12-api_768w.jpg 768w",
            alt: "RESTful API's",
        },
        type: "Project",
        section: "Viper",
        date: new Date("2022-11-10"),
        link: "https://github.com/huesoskywalker/viper-nextjs-mongodb",
        author: "huesoskywalker",
    },
    {
        title: "Entry point",
        image: {
            src: "/img/portfolio/tall/typescript-handbook_1920w.jpg",
            srcset: "/img/portfolio/tall/typescript-handbook_1920w.jpg 1920w, /img/portfolio/tall/typescript-handbook_768w.jpg 768w",
            alt: "TypeScript Book",
        },
        type: "Book",
        section: "TypeScript",
        date: new Date("2023-01-10"),
        link: "https://www.typescriptlang.org/docs/handbook/intro.html",
        author: "typescriptlang.org",
    },
    {
        title: "Real State",
        image: {
            src: "/img/portfolio/wide/real-state_1920w.jpg",
            srcset: "/img/portfolio/wide/real-state_1920w.jpg 1920w, /img/portfolio/wide/real-state_768w.jpg 768w",
            alt: "Real State Map",
        },
        type: "Project",
        section: "Google Maps",
        date: new Date("2023-08-01"),
        link: "https://www.youtube.com/watch?v=USTM_HdKN2I",
        author: "huesoskywalker",
    },
    {
        title: "Chicago Medical",
        image: {
            src: "/img/portfolio/wide/chicago-medical_1920w.jpg",
            srcset: "/img/portfolio/wide/chicago-medical_1920w.jpg 1920w, /img/portfolio/wide/chicago-medical_768w.jpg 768w",
            alt: "Chicago Medial",
        },
        type: "Project",
        section: "Web Development",
        date: new Date("2023-10-10"),
        link: "https://chicago-medical-checkup.vercel.app/",
        author: "huesoskywalker",
    },
]
